### ISSUE TITLE
"Notice: no station supplying ...." loop 

### ISSUE THREAD

**Issue by GoktugOzturk** [Yousei9/Factorio-LogisticTrainNetwork#12]
Hi,

Sometimes LTN starts putting no station notices in a loop. I wait for sometime but it doesn't stop. 
![untitled](https://cloud.githubusercontent.com/assets/1000956/24073524/4620e9fa-0c01-11e7-83bf-aef949625b0b.png)

I guess it should stop when all requested items create notice. Then it should wait for a time.

Until a patch is live, is there a way to disable this notices?

**Comment by Yousei9** [comment]
From Known Issues:
> Message spam "no station supplying ..." when using Bobs, Angels or similar mods.
Increase message_filter_size in config.lua
