### ISSUE TITLE
Feature Request: "Do not provide from this station" signal

### ISSUE THREAD

**Issue by GoktugOzturk** [Yousei9/Factorio-LogisticTrainNetwork#13]
I have a mineral processing station which requests various minerals. Sometimes it receives more than it requested and item request signal becomes positive. 

When it is positive LTN create some routes to receive these extra items. But there are only unloading inserters in this station so train get stuck waiting in this station.

If there is a signal "Do not provide from this station" It should solve this problem.
I know i could solve this with combinators but this feature would be great.

**Comment by Yousei9** [comment]
This has been answered several times in the forum thread.
Use a decider combinator each < 0 = each input value.
