### ISSUE TITLE
non localised resource names

### ISSUE THREAD

**Issue by zocke1r** [Yousei9/Factorio-LogisticTrainNetwork#17]
Is it possible that the localised name is used instead of the internal one for missing resources, as the internal resource name doesn't really help in most cases

**Comment by Yousei9** [comment]
I'm afraid that's not easily possible as the message filter requires messages to be buffered.
Having different localized strings in the buffer would cause MP desync.

**Comment by zocke1r** [comment]
would it be possible to load english localized name and display that, so that every one has the same localised strings?

**Comment by Yousei9** [comment]
Most console messages in 1.0.x are already localized. You can get the alpha on github,
Let me know if you find any bugs.
