### ISSUE TITLE
recipe doesn't work when modified by other mod

### ISSUE THREAD

**Issue by judos** [Yousei9/Factorio-LogisticTrainNetwork#18]
Hi Yousei9,
I'm modder of hardCrafting and I just experienced a very rare and weird issue :)

Depending on the order of mod loading the recipe for the logistic-train-stop won't contain the correct resulting items (In the case of this issue, just contains normal train-stops which is not usual).

The issue is that hardCrafting modifies the result of the normal train-stop and adds another resulting item: scrap-metal. That means the prototype does not contain .result but rather the .results variable.
If LTN is loaded afterwards it will copy the prototype but not be able to change the result in lib.lua:

```
function copyPrototype(type, name, newName)
  if not data.raw[type][name] then error("type "..type.." "..name.." doesn't exist") end
  local p = table.deepcopy(data.raw[type][name])
  p.name = newName
  if p.minable and p.minable.result then
    p.minable.result = newName
  end
  if p.place_result then
    p.place_result = newName
  end
  if p.result then
    p.result = newName
  end
  return p
end
return copyPrototype
```

Can you add a check to make sure the result will also be changed if the recipe uses the .results variable?
I tested it with this fix and it would work:

```
	if p.results then
		for _,itemTable in pairs(p.results) do
			if itemTable.name == name then
				itemTable.name = newName
			end
		end
	end
```

Thanks for your help :)

**Comment by Yousei9** [comment]
Thanks for the reporting this very specific and rare bug. 
I've been using this copyPrototype since my very first mod and never stumbled across this.

**Comment by judos** [comment]
@Yousei9 good point. I will also improve that in hardCrafting. Thanks for the hint and for the fix! 👍
