### ISSUE TITLE
logging levels

### ISSUE THREAD

**Issue by zocke1r** [Yousei9/Factorio-LogisticTrainNetwork#19]
given the amount of spam that logging level 2 generates just from all the route announcement messages i started using logging level 1 with the expectation that now i will only get to error messages like no station found supply resource or train timed out, but given that i havent seen either message after switching to logging level i would say this assumption was wrong. Because of that i would greatly appreciate it when it would be possible to filter out the other lvl 2 messages and still get those errors

**Comment by Yousei9** [comment]
What are route announcement messages?
Give me a list of either localized messages or english messages with your proposed log level and I'll see what I can do.

**Comment by zocke1r** [comment]
with route announcement messages i mean the creating-delivery messages, as they announce that a route from station x to station y carrying resource x.  

Messages i would still like to see are the delivery-removed-timeout and no-provider-found.

**Comment by Yousei9** [comment]
What messages feel important to someone is very different.
I grouped messages by "severity".
level 1: errors
level 2: notifications
level 3: in game debug
level 4: complete debug

delivery-removed-timeout and delivery-removed-train-invalid are warnings and potentially could move to lvl1.
no-provider-found, no-train-found are the very definition of notifications.

For everyone to have only the messages they want I'd need a gui listing all messages allowing players to check messages as active.
Perhaps with the promised mod config settings for 0.15, but that's currently my lowest priority.

**Comment by Yousei9** [comment]
I consider moving warnings to level 1 solved this for you.
