### ISSUE TITLE
inactivity type "and" +"or"  duble schedule issue

### ISSUE THREAD

**Issue by kallahil** [Yousei9/Factorio-LogisticTrainNetwork#21]
double schedule  issue

inactivity type "and" +"or"  duble schedule 
train select item count Excess.
 

![2](https://cloud.githubusercontent.com/assets/28151599/25535913/a9c8dbb0-2c73-11e7-8780-59868eadb05b.PNG)

![default](https://cloud.githubusercontent.com/assets/28151599/25535687/f4c83e72-2c72-11e7-8916-ab3b084e0fb8.PNG)

![3](https://cloud.githubusercontent.com/assets/28151599/25535918/af420904-2c73-11e7-8409-04307f9b9443.PNG)

**Comment by Yousei9** [comment]
Not a bug.
Your station design simply doesn't count how much is loaded.
AND 2s inactivity is for loaders to finish so they don't get stuck
OR 120s inactivity is to make force stuck trains out of stations
