### ISSUE TITLE
LTN Research Dependency

### ISSUE THREAD

**Issue by Pasukaru** [Yousei9/Factorio-LogisticTrainNetwork#23]
Producing a LTN Station requires red chips. 
There is one minor problem when playing with 0.15 complex recipes and complex research modes enabled: The LTN research can be done without actually having red chips researched. Thus, you are not able to build it. 

I think the LTN research should therefore depend on "Advanced Electronics" (in addition to the existing "Automated rail transportation" dependency) when the above mentioned modes are set.

**Comment by Yousei9** [comment]
Stops also need red chips on normal mods.
As I recall factorio does the same implicit dependencies to keep the tech tree from cluttering with dependencies.

**Comment by Pasukaru** [comment]
I just did a test how it looks with the dependency.
![image](https://cloud.githubusercontent.com/assets/1093680/25563236/e4a66cd2-2d97-11e7-95e0-74992ee9cc4c.png)

I think it's ok and doesn't look too bad.

**Comment by Yousei9** [comment]
Even for a single research it  really hurts my ocd seeing two dependency lines crossing each other.
If all techs used every possible dependency the tech tree would be so full with dependency lines crossing each other it'd become impossible to decipher with the current way it's displayed.
