### ISSUE TITLE
Multiple trains claim the same resources when there is not enough resources to satisfy a request

### ISSUE THREAD

**Issue by nullberri** [Yousei9/Factorio-LogisticTrainNetwork#3]
Version: 0.3.2
When there is not enough resources to satisfy demands, multiple trains will claim the same resources.

for example if there is 5000 Steel being requested but only 1000 available, multiple deliveries will be created against the same 1000 steel, leaving many trains trying to load up for a non existent resource. 

One possible solution below. 

```
--return name of station with highest count of item or nil
function GetStationItemMax(item, min_count ) 
  local currentStation = nil
  local currentMax = min_count
  for stopID, storage in pairs (global.Dispatcher.Storage) do    
    for k, v in pairs (storage.provided) do      
      if k == item and v > currentMax   then
        local ltStop = global.LogisticTrainStops[stopID]
        if ltStop then
          local outstanding = GetExistingDeliveries(ltStop.entity.backer_name, item);
          if v - outstanding > currentMax and v - outstanding > 0 then
            if global.log_level >= 4 then printmsg("found ".. v .."  ".. k.." at "..ltStop.entity.backer_name) end
            currentMax = v - outstanding
            currentStation = {entity=ltStop.entity, count=v - outstanding, maxTraincars=global.Dispatcher.Storage[stopID].maxTraincars}
          else
            if global.log_level >= 4 then printmsg("found ".. v .."  ".. k.." at "..ltStop.entity.backer_name.. " But it was already claimed") end
          end
        else
          if global.log_level >= 1 then printmsg("Error(GetStationItemMax): "..stopID.." no such unit_number") end
        end
      end
    end --for k, v in pairs (storage.provided) do      
  end
  return currentStation
end


function GetExistingDeliveries(station, item)
  local count = 0
  for _, value in pairs(global.Dispatcher.Deliveries) do
    if value.from == station and value.item == item then
      count = count + value.count
    end
  end
  return count;
end
```

**Comment by Yousei9** [comment]
Thanks, i fixed it in a very similar way in my local version.
Still working on some other bugfixes for 0.4 though

`--return name of station with highest count of item or nil
function GetStationItemMax(item, min_count ) 
  local currentStation = nil
  local currentMax = min_count
  if use_Best_Effort then -- Best effort will ship below requested size
    currentMax = 1
  end
  for stopID, storage in pairs (global.Dispatcher.Storage) do    
    for k, v in pairs (storage.provided) do      
      if k == item and v > currentMax then
        local ltStop = global.LogisticTrainStops[stopID]
        if ltStop then
          if global.log_level >= 4 then printmsg("found ".. v .."  ".. k.." at "..ltStop.entity.backer_name) end
          currentMax = v
          currentStation = {entity=ltStop.entity, count=v, maxTraincars=global.Dispatcher.Storage[stopID].maxTraincars}
          -- subtract min_count from storage.provided so we don't request the same items multiple times
          global.Dispatcher.Storage[stopID].provided[k] = v - min_count
        else
          if global.log_level >= 1 then printmsg("Error(GetStationItemMax): "..stopID.." no such unit_number") end
        end
      end
    end --for k, v in pairs (storage.provided) do      
  end
  return currentStation
end`
