### ISSUE TITLE
LTN station spam is server-wide, not limited to force.

### ISSUE THREAD

**Issue by oddstr13** [Yousei9/Factorio-LogisticTrainNetwork#40]
I am on a different force than the LTN setup spamming my chat.
![screenshot](https://thoas.feralhosting.com/oddstr13/sharex/image/factorio_2017-05-29_19-05-33.png)

**Comment by Yousei9** [comment]
Your message filter time out must be pretty low if you get spammed by messages. default is 5 min

Using LTN between multiple forces is mostly untested.
I made sure LTN will only run deliveries between stations with trains of the same force, but that's as far as trains and multiple forces can be made to work well together.

**Comment by oddstr13** [comment]
That is default timeout. The problem is that you are using `game.print`, not `force.print`, and thus, everyone in the game regardless of force gets the messages.
