### ISSUE TITLE
Bug on non existing items

### ISSUE THREAD

**Issue by Joey92** [Yousei9/Factorio-LogisticTrainNetwork#43]
It looks like there is something unhandled when items get removed, because a mod updated in the meantime while the train was on it's way or something like that.
Here is the error message:

```
Error while running event LogisticTrainNetwork::on_train_changed_state (ID 23)
Unknown item name: angels-barrel-mineral-sludge
stack traceback:
	__LogisticTrainNetwork__/control.lua:1170: in function 'UpdateTrain'
	__LogisticTrainNetwork__/control.lua:514: in function <__LogisticTrainNetwork__/control.lua:513>
```
In this case i guess angels-refining mod updated its items. After this error message factorio goes back to the main menu.

**Comment by Yousei9** [comment]
Will be fixed in next version
