### ISSUE TITLE
"Provide Threshold" seemingly not doing anything

### ISSUE THREAD

**Issue by Xasin** [Yousei9/Factorio-LogisticTrainNetwork#48]
Hi! 
I absolutely love the way this mod has developed over the last couple of weeks, and that it has been getting a few more options with which to work with! 

One problem I am having is understanding "Provide Threshold" for providing stations though. I have the following problem:

When a station (without either provide or request thresholds set) requests X amount of a material, but the requested amount is below the default threshold of 1000, nothing will happen. 
EVEN IF another station is providing the material, with a provide threshold set that is below the amount the station is requesting.

At the same time, however, once I set a request threshold for the requesting station, EVERYTHING gets overridden - both the default thresholds as well as the provide thresholds for the providing stations.

As such, I am a bit confused as to what the provide threshold is used for since it has no apparent function the way I am seeing it right now.

**Comment by Yousei9** [comment]
> When a station (without either provide or request thresholds set) requests X amount of a material, but the requested amount is below the default threshold of 1000, nothing will happen.

Requests trigger at x*-1 >= threshold. My test scenarios trigger at exactly -1k.

> At the same time, however, once I set a request threshold for the requesting station, EVERYTHING gets overridden - both the default thresholds as well as the provide thresholds for the providing stations.

That's not possible with the way every station uses either a threshold signal or the mod setting. 
Perhaps you use one constant combinator for request threshold and desired amount *-1.

Signals, thresholds and station setups are explained in the [forum thread](https://forums.factorio.com/viewtopic.php?f=94&t=36976).

**Comment by Xasin** [comment]
Hm, in this case, I must have misunderstood the use of Provide Threshold. 

My assumption was that it meant "Only provide for orders requesting more than this amount"
The wording of the description was a bit ambiguous, as it does not reference the station's stock itself, but instead mentions an "amount of items required"

I did not immediately see the graphic below it since I only briefly looked at the update news ... That was my mistake.

I would not mind seeing an option like what I described though, as it would allow one requester station to receive, say, Iron in batches of 5k, while only using requests of 100 when it comes to more expensive materials - but a bit of circuitry will surely allow me to do this either way :)

I am sorry for the troubles.

**Comment by Yousei9** [comment]
Tell me a way how to do have thresholds/item at one station without generating threshold signals for every potential item and fluid and I will add that functionality.

**Comment by Xasin** [comment]
Well, you don't have to use a separate signal for every different item on a station.
In my setup, for example, I have stations directly at the iron/copper mining sites, together with smelting, and a separate station providing processed goods like electric circuits or engine units.

If I could set the iron and copper plate stations to only deliver for requests with more than 4k, while leaving my station supplying engine units at a lower minimum order size like 100, then the requester stations could have larger buffers of iron and copper, and equally also receive large orders, while not having to stock up as much on the expensive items, and not requiring such big deliveries for those.

Although I suppose I could also set up multiple requester stations close to each other, one for "bulk items" and the other for the expensive ones, or use some other means of regulating the requests, so adding such a functionality is definitely not a necessity.

**Comment by Yousei9** [comment]
This would only work for a select few specific setups.

Imagine a network with multiple requester and provider each with different fill levels, a mix of different items provided and requested and different thresholds. That's the kind of network I assume to ensure LTN will work with practically anything a player can design in Factorio.

**Comment by Xasin** [comment]
Hm ... I am a little confused anyways by the implementation of a provide threshold, since such a thing could be done with a single constant combinator subtracting the to-leave amount of the items, and a decider combinator ensuring only positive values to be forwarded to the station ... 

But at the same time, I suppose my own ideas can be realised with a few combinators placed in the right ways.

Sorry for the time consumed. I think I got it figured out now ^^
