### ISSUE TITLE
error encoding train composition for trains longer than 31 carriages

### ISSUE THREAD

**Issue by kcollasarundell** [Yousei9/Factorio-LogisticTrainNetwork#55]
![2017-08-07 21_20_21-factorio 0 15 32](https://user-images.githubusercontent.com/393998/29024614-3e1c9356-7bb6-11e7-83a3-dc030c3db99a.png)

Tested in real and creative mode as soon as you add a 32nd car and send it to an LTN station the game crashes. 

appears to be related to https://github.com/Yousei9/Factorio-LogisticTrainNetwork/blob/master/control.lua#L1607 I'm not great with lua so i don't know where that points but i imagine that a 5 bit length value somewhere is not fitting.

**Comment by Yousei9** [comment]
I always expected some error when trying to encode 32 carriages. Factorio's circuit network is only 32bit integer and can't take values > 2^32/2-1.

I'll look into adding safeguards and potentially expanding train composition from signed int (31 carriages) to unsigned int (64 carriages).

**Comment by Yousei9** [comment]
Fixed: trains with 32+ carriages won't have composition signals.

**Comment by kcollasarundell** [comment]
<3 Thanks so much for fixing this. My overengineered farl train is very greatful
