### ISSUE TITLE
LTN does not Provide Crotinnium Ore

### ISSUE THREAD

**Issue by leonorpw** [Yousei9/Factorio-LogisticTrainNetwork#57]
Hello, we have a MP game running with more then 100 LTN stations right now. Today we tried to add Crotinnium Ore but no trains comming. We store the ore in a Warehouse, but we also tried to use smaller chest, but nothing. Also we triedto provide the ore on 

Base Mods we use:
Angels Mod
Bobs Mod

**Comment by Yousei9** [comment]
In order for me to have any way of helping you enable debug logging and send me factorio-current.log.

**Comment by leonorpw** [comment]
Here is a 5 min factorio log with enabled debug mode.
The Crotinnium Ore Provider is Crotinnium-Mining-Ore-Out and the requester is Crotinnium-Crushing-Ore-In.

We just nocticed that a other station does not request Iron Ore anymore . (Station name: Concrete-In) This used to work before, and we didnt change it.
[5-min-factorio-log.zip](https://github.com/Yousei9/Factorio-LogisticTrainNetwork/files/1222962/5-min-factorio-log.zip)

**Comment by Yousei9** [comment]
I assume Crotinnium is still angels-ore4, he really should've named those better.

```
9976.044 Script @__LogisticTrainNetwork__/control.lua:1451: (UpdateStop) Crotinnium-Mining-Ore-Out provides item,angels-ore4 93059(8000)
9976.169 Script @__LogisticTrainNetwork__/control.lua:881: request 15/24: 40000(16000) item,angels-ore4 to Crotinnium-Crushing-Ore-In min length: 4 max length: 4
9976.169 Script @__LogisticTrainNetwork__/control.lua:925: No station supplying item,angels-ore4 found.
9976.169 Script @__LogisticTrainNetwork__/control.lua:881: request 16/24: 40000(16000) item,angels-ore4 to Jivo-Crushing-Ore-In min length: 4 max length: 4
9976.169 Script @__LogisticTrainNetwork__/control.lua:925: No station supplying item,angels-ore4 found.
```

This looks like your requester and provider are limited to different train sizes.

**Comment by leonorpw** [comment]
Okay so ... well that hurts. We had 2 requester stations linked together with green wires on the same electric pole which resulted in the train limits of 2/2/1 to add up to 4/4/2 *facepalm*
The problem with the iron ore requester was fixed by reconnecting the wires of the station, altho the connections were the same afterwards.

Anyways thanks for the really quick and helping response!
