### ISSUE TITLE
Mixed loading stations - Items left in inserters

### ISSUE THREAD

**Issue by Vektah** [Yousei9/Factorio-LogisticTrainNetwork#7]
I have a few mixed loading stations that have logistics chests loading into logi train stops. They look like this:
![image](https://cloud.githubusercontent.com/assets/2247982/22586189/787962b6-ea4f-11e6-9cf6-21b953ee9d0f.png)

A bunch of chests wired to the lamp, a bunch of filter inserters wired to the constant output. 

The problem is, as you can see in the screenshot, the train leaves while the inserters are still moving, causing many of them to get stuck with an item in the hand. These items get dropped into the next unsuspecting train, which is probably going to pick something different up.

I'm hoping there is an easy fix, if not I was thinking of PR'ing a change that moves the train un/loading logic into the mod, polling every few ticks to see if the conditions were met. If they were met then stop outputting on the constant combinator, wait a few ticks then update the trains route.

**Comment by Yousei9** [comment]
Sadly there is no "sane" way to fix this inserter behavior. Look for "smart loader" in factorio forums to see the combinator contraptions needed to somewhat control how many items inserters load into wagons.
With 0.15 filter inserters will supposedly will be able to grab a set number of items. (e.g. stack size 12, send 6 iron plate and it'll grab 6 instead of 12)

**Comment by Vektah** [comment]
In my case the trains aren't full though, its just leaving before inserter drops. if the output signal stopped before the train left the inserters would finish dropping their stack first

**Comment by Yousei9** [comment]
Making trains leave once the requested amount is loaded prevents inserters from loading forever and get stuck in the end anyway.

Add a simple pulse counter to your inserters.

**Comment by Vektah** [comment]
Hmm, so by pulsing them all at the same time you avoid half loaded timing issues? Neat.

**Comment by Yousei9** [comment]
Here's a blueprint of an overly simplistic Provider/Requester station using a pulse counter.
`H4sIAAAAAAAA/+VZWY+rNhj9KxEPVRe4Yk+iW/oLqqqq2qerCnnAIVbBprZJJ4ry32szJOxgz2Sku8xLJrJ9+NZzPoeUbHKSgHwTRxeIOeIIsuhywaCAkVHA
FFWFBXOYcIoSqyQ5NMySMLGN4OjyHNkfAvMcWY7zIbiaCcFY7BRLAuKT4Rh/RxcKUwFXI59jlEbe1ex8c5yr/DOb5zFOAcqO3BIfef9Blls/x2435yRDjAur
5CFsMU5Ki1S8rPjg5M1Gu7GRU5LHT/AITojQ6HJAOYdUOs1QhkEeXfi5FPgnRHkFhBmNbfWilVF4NiRMhXnkmAin8DmSXih533d3ygOERw6s2J8gmlSIx2Il
bc4cEGU8VnEH4DM/IpzVLmHGgfDKFv8WJaCAC3jjF7FUMSjgcyKixGkF1XwN13wdeDnM780eS1jzhLC0pn/CfYnLXoYlRfTFnsh9fYoL8NyYl0Oc8eM9z/49
z+YAAXFY3I4fAOPyPGYlodx6gjlvK8W27QYkXAepxEaaUXEynYXZrsOwMkdcOD51fLd4PCc4s45A7ExFRTJIZ1BEvlatWDy/EtE6b8sI7iKCqKDkn2UATwFA
xRB/EWfxaKDKH74eXe409obt3hQmSBTgfOPJ/cF62zU4LTMxJWr69c/frATQjFj/gYzgeWqKDPOF8PXxynNcpyE+UFLENelGB5AzqErkNeV/MtzJRRGMhpRH
nL+aB7/dqyy/nqr6Oj313ffN7AnzdmFt3/vqboXFQhYhXgxCD8HvrrkjuKtmLfpfTC02sgtPkHaEd6oaa6FVy+q+H831bLjjIWy2lgeFoJJqrXp3272AIn4s
oJwS5tJdTwnuerpbKN2M3zIEkmM325ZjkhKKZMsnGj/qZbvGmknmRDiDTj4mlocBnhKo6Ql4PW63PBYkhTE5xK3Pzj3HFII0lsOBDC0XhulMhf16milWf76e
7nNkcoRiuKDw30p8Dj3uOqzl5Cud0CWsQSbCxxHWTPkOZ3r98n07TTkDEVigJHfEKLP8FPRBQy32sYd9NN1ATTm97QLWnQYVJUVnGHkNI9jrZfjuhOC664Tg
qhMCEI87Qauk5CTbZyqP0mutdlUI02O71Qp7hfDz49pVa8YdSv9sE7q2VtfpS76Ccj1c8e2u4P/0noJfh29e8AcT8Vp0fe3oKozPX/I85WmFV/XSpX7n6sue
2789eQvXJG8/PR4NAJcuU+H8mkTXKKtQRyrDz1QpR62kqpQKv3a8QSnv6/VSvUmiqI6jnoqEho+ZqYN3GqlHPmiO1MG3OFG7235HKwu2Z/cP6t3Zd9oKs/uq
9dtbvrCPiFaVdLYTNb3eSAoXbO+h8/RWd56e8usbmKeHUr/QnoFWP3bfmqmOL/e3iUqaOSUoA+7x5/l71X653URJbcXiW6nxO8Rr+wq2/cl2Y23+wqJsKQP5
5vemdL/746Zrm+8rhnC2qbMJ6Q/G9SOFvKJ4E3+EOP0fG9wPFxMfAAA=
`

A faster way for only providers is this
`H4sIAAAAAAAA/91bUa+bOBP9K1d5Di02xgZ1sy/7tNJq9T18b9UqosG911oCCJyrXkX572ty0+YOGcAGEinpS5sam2HOMHN8GKfFU1ZskuxpvdrLXCutZL3a
7/NkK1cL+aOsZF17ukryuiwq7X2TmV4sy6I2Fxb5av9j5YlP4fJt5bFP4WGZqkpujiP8sHRZJBpYpNbJ5l9P5bWstKzwyUEzeVPkuiqy9Tf5kryqolrtN6ra
7JRem5H0NOe7qmq9rtVznmSrvX4rzR1eVaV3SbZYnm54HPTkq6ze9IvKnxfHtY0duV5R889tmVSJNjdY/NYMnW7ykuTpupJJut4WqVyR46T8/XGMX78uyOKf
1b6SqfHx0d1va5WuaHw4LJ8rKXPw3+zQ/LFygbh3FwQUdUFgHv/8KwIOsQqscI7o5FOiM7x7aAIUmghAQ4h9sPK79wjreF8/ekS4B2swR7CyKcHK7h4agUIj
YLAyd2zIHNjQKdiQe8eGERQbkzoAOO5Z3p8Dm6FF+rDx7x4avPwSmOQptU/y9+8SvOwRmOWJe5ofSgI2awxloz5o6N0jw1FkTHSCYA1/3ab5ZR25959m8RJI
YA2kxDlwh5iFzRpDFCeplH7ZSq02nvHKN5U3XkHNCDB4ztPPCNU4RErL7U98VFXkXpklWn4ExiP+siilAaa58+LzYlnsdLmzXeiAw4XwRt5c+3VB8eERSM2x
6xna9GxlqnZbT2ZmpDJwlUUm24zlVATo6V0aZm+w9mfFs6qPofAia+2VSV2rV+mVVfGq0i4ZwP5m+I4TyxTfVWbyxID+QPozRvMKr4vv63NE2VJabGvVb5G4
skU+SCUBn4CacEQN33rRGFrEJlgUOlqEp9sA8oRATLCIO1oUdUU2sChwDqvwymHFoYGxs4H8ygaG0EAyAVPmiCnBN08BVMgYNMkiRweOdlC4JQh9Z5DYTUFi
7gaSKxsIcxWbkquIaxTh6TOA3JAF401yLfkET5+sFddT0qezSXj+ZFCnYO5Ewb9uYDFYllnoauC17YMlkcXjMaWuWQvPnnCPSNoh15PonKx1fUsprsYwWMAZ
d8WXXhnfeGJpuHLiZa3KADcbw7XStVQyWCoD+DP2cZD5xVXAiVWinl+0Z/7K2rWAGuv8j5s1ajfPHzcvGjeNj5vGxk0b55NxHhl3r3EPNs6L4yDrC5BWHkzM
eHchjo8vUPP+/JrfXzDfJ1wrH/AQfQPjY91cvlvWNEOoPJXGC5hWdBqjp7FNURojPghAzlqJdXLhra+NzsX+tPMmUN9hV3E0LKXCnZJHt7N1uphhjWGM931w
WEfFlG1m5GgRTn155IwYvyViwF10gru4m7uIjzM1Dku9GCu13MJ9Au4axHTpzMF9uAYrIBMXzkT3pDHcxH2QlAu4qbEWYOzzPiSx4pJUTpSkHNDDv8OJVtNW
r0n9hIG6EgZ6VcIgcMJAfDE7Y7DXqW4S5JBsRFNSLHGMMoLvkwTM+tGUIulIvQjp6IiDmTTC+jdtBKKbIAo5RuRcoW5nagQzbDSBoDkDjculEaxPkTM7ordz
3oCcYKnJ3MTUVt0Ix+NMXXHGRehovuLqnPVwIh61EjGUxa2bJ4IhMEf2UcBqNqmT4qIw2vVSHDHq7qUgrX4tW9HP/tMrpGdhi1zD0RhXpaML5RlgHndr1rHr
5z/X7SE0JcZ3P+2rOr4mNYJT7tW6KL33aGirTmfb+oP1zLtsmrCMvW/H2NyZwCTLE1XrirALD3TwjA8Po/KLZ4mBm+dsKUvyy4YyHzSU/W6GdrU0y2eFcZKu
dtL6ZRp8WEQopLhQ+NO6zsx0EvuC8Xj3dHQ1WFPCBIsCzsQv0Jc9K1zkMnQNap+a+Iiu8/f3c1pjs+hfw+JolQUmd9AXyXG1LcbaTHol0wdxB84w4ta5Hp+6
Ry2fIWrDCVHLHwgmgXOEOG7BhG3gerXFB3FPR5e+T1v+4e5hzGYI42BCGLNHwgnXCpu4hccI4R5rmDXQB2cNYsShVzpD4JIJgUseKHAjXH5sEgoM3MAdJ386
TgNLWBzRehCYus4W+i2Y7A/VP5R7cCGziVroHvdsM5Ao7E/ETTjM9iAgdaiQMTzI1gfY8MG2B3EVvnkh7dOZI45nzsD6Bkif/QmuGQ5wXSxxWKrN0bU9LAZT
eg5nqex01V////vJe/rTcKbPfxxpz9P/fmrfhy+V1Lsqf1p/kXn6H3XLsuplRgAA
`
