### ISSUE TITLE
Mixed loading stations - Merged requests never complete

### ISSUE THREAD

**Issue by Vektah** [Yousei9/Factorio-LogisticTrainNetwork#8]
I have a few mixed loading stations that have logistics chests loading into logi train stops. They look like this:
![image](https://cloud.githubusercontent.com/assets/2247982/22586189/787962b6-ea4f-11e6-9cf6-21b953ee9d0f.png)

Occasionally LTN will merge two orders from these mixed stations (awsome!). Unfortunately the constant combinator dosent update as the train unloads, so it only ever loads the first item and gets stuck waiting forever.

Like This is related to https://github.com/Yousei9/Factorio-LogisticTrainNetwork/issues/7, I'm hoping for an easy solution.

If not I'm thinking about PR'ing similar change that uses the polling logic from #7 to change the combinators output every ~30 ticks or so between the items that are still waiting to be loaded.

Thoughts?

**Comment by Yousei9** [comment]
As I said in #7 there's currently no sane way to prevent inserters from grabbing excess items.

Sure I could scan along every track for inserters and turn them 180° while no train is in the station. That would take a ton of update time and not fix the real issue of inserters always grabbing stack size from chests.

**Comment by Vektah** [comment]
This isnt about excess, Its that the train cant pick up both types of items because the filter only applies to the first one

**Comment by Yousei9** [comment]
Stack Filter inserters have only one filter slot. Nothing I can change about it. Use one inserter/item or normal filter inserters which have 5 filter slots.

**Comment by Vektah** [comment]
I guess that works...

I was just thinking that if the output was updated once an item was fully loaded the filter would move to the next one.
